In [32]:
import pandas as pd

# Tab 3.44
## Sheet 1 - Proporção de diagnosticos de depressão de acordo com o sexo

In [33]:
tab3_44_sexo = pd.read_excel('dados/3.44.xls')

### Removendo colunas desnecessárias

In [34]:
tab3_44_sexo.dropna(inplace=True)
tab3_44_sexo.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 5','Unnamed: 6','Unnamed: 8','Unnamed: 9'],inplace=True)

### Renomaendo colunas

In [35]:
colunas = ['Estado','Diagnostico Depressão Total', 'Diagnostico Depressão Masculino', 'Diagnostico Depressão Feminino']
tab3_44_sexo.columns = colunas

In [36]:
tab3_44_sexo.head(5)

,Estado,Diagnostico Depressão Total,Diagnostico Depressão Masculino,Diagnostico Depressão Feminino
8,Brasil,10.2,5.1,14.7
9,Urbana,10.7,5.4,15.1
10,Rural,7.6,3.5,12.3
11,Norte,5,2.9,7
12,Rondônia,9,5.1,12.8

### Removendo linhas com dados totais do brasil e de regiões, mantando apenas as colunas de cada estado

In [37]:
tab3_44_sexo.drop(tab3_44_sexo.iloc[0:3].index,inplace=True)
selecao = (tab3_44_sexo['Estado'] == 'Norte') | (tab3_44_sexo['Estado'] == 'Nordeste') | (tab3_44_sexo['Estado'] == 'Sudeste') | (tab3_44_sexo['Estado'] == 'Centro-Oeste') | (tab3_44_sexo['Estado'] == 'Sul')
tab3_44_sexo.drop(tab3_44_sexo[selecao].index,inplace=True)
tab3_44_sexo.reset_index(drop=True,inplace=True)

In [38]:
tab3_44_sexo.reset_index(drop=True,inplace=True)

In [39]:
tab3_44_sexo.loc[0:7, 'Região'] = 'Norte'
tab3_44_sexo.loc[7:16, 'Região'] = 'Nordeste'
tab3_44_sexo.loc[16:20, 'Região'] = 'Sudeste'
tab3_44_sexo.loc[20:23, 'Região'] = 'Sul'
tab3_44_sexo.loc[23:, 'Região'] = 'Centro-Oeste'

### Corrigindo tipo de colunas numericas

In [40]:
tab3_44_sexo.dtypes

Estado                             object
Diagnostico Depressão Total        object
Diagnostico Depressão Masculino    object
Diagnostico Depressão Feminino     object
Região                             object
dtype: object

In [41]:
colunas_numericas = ['Diagnostico Depressão Total', 'Diagnostico Depressão Masculino', 'Diagnostico Depressão Feminino']
tab3_44_sexo[colunas_numericas] = tab3_44_sexo[colunas_numericas].apply(pd.to_numeric, errors='coerce')
tab3_44_sexo.head()

,Estado,Diagnostico Depressão Total,Diagnostico Depressão Masculino,Diagnostico Depressão Feminino,Região
0,Rondônia,9.0,5.1,12.8,Norte
1,Acre,6.0,2.5,9.3,Norte
2,Amazonas,4.2,2.9,5.4,Norte
3,Roraima,5.1,2.8,7.3,Norte
4,Pará,4.1,2.5,5.6,Norte

## Sheet 2 - Proporção de diagnosticos de depressão por grupo de idade

In [42]:
tab3_44_idade = pd.read_excel('dados/3.44.xls',sheet_name='grupos_de_idade')

In [44]:
colunas = [2,3,5,6,8,9,10,12,13,15,16,18,19]
tab3_44_idade.dropna(inplace=True)
tab3_44_idade.drop(columns=tab3_44_idade.columns[colunas],inplace=True)
tab3_44_idade.head(10)

,"Tabela 3.44.2.1 - Proporção de pessoas de 18 anos ou mais de idade que referem diagnóstico de depressão por profissional de saúde mental, por grupos de idade, com indicação do intervalo de confiança de 95%, segundo as Grandes Regiões, as Unidades da Federação e a situação do domicílio - 2019",Unnamed: 1,Unnamed: 4,Unnamed: 7,Unnamed: 11,Unnamed: 14,Unnamed: 17
8,Brasil,10.2,5.9,11.3,13.2,11.8,10.2
9,Urbana,10.7,6.2,11.7,13.9,12.1,10.8
10,Rural,7.6,3.8,8.8,9,9.7,6.6
11,Norte,5,3.2,5.6,5.7,6.3,5.2
12,Rondônia,9,7.2,9.9,6.9,10.9,6.6
13,Acre,6,2.7,7.6,5.9,9.7,2
14,Amazonas,4.2,4,4,5.8,6.6,2.2
15,Roraima,5.1,4.8,5.2,3.4,7.1,4.1
16,Pará,4.1,1.7,5.1,5.1,4,6.4
17,Amapá,4.5,4.8,3.7,4.3,10.7,5.5

In [48]:
colunas = ['Estado','Diagnosticos Depressão Total','Diagnosticos Depressão 18 a 19 anos','Diagnosticos Depressão 30 a 59 anos','Diagnosticos Depressão 60 a 64 anos','Diagnosticos Depressão 65 a 74 anos','Diagnosticos Depressão 75 anos ou mais']
tab3_44_idade.columns = colunas
tab3_44_idade.head(10)

,Estado,Diagnosticos Depressão Total,Diagnosticos Depressão 18 a 19 anos,Diagnosticos Depressão 30 a 59 anos,Diagnosticos Depressão 60 a 64 anos,Diagnosticos Depressão 65 a 74 anos,Diagnosticos Depressão 75 anos ou mais
8,Brasil,10.2,5.9,11.3,13.2,11.8,10.2
9,Urbana,10.7,6.2,11.7,13.9,12.1,10.8
10,Rural,7.6,3.8,8.8,9,9.7,6.6
11,Norte,5,3.2,5.6,5.7,6.3,5.2
12,Rondônia,9,7.2,9.9,6.9,10.9,6.6
13,Acre,6,2.7,7.6,5.9,9.7,2
14,Amazonas,4.2,4,4,5.8,6.6,2.2
15,Roraima,5.1,4.8,5.2,3.4,7.1,4.1
16,Pará,4.1,1.7,5.1,5.1,4,6.4
17,Amapá,4.5,4.8,3.7,4.3,10.7,5.5

In [49]:
tab3_44_idade.drop(tab3_44_idade.iloc[0:3].index,inplace=True)
selecao = (tab3_44_idade['Estado'] == 'Norte') | (tab3_44_idade['Estado'] == 'Nordeste') | (tab3_44_idade['Estado'] == 'Sudeste') | (tab3_44_idade['Estado'] == 'Centro-Oeste') | (tab3_44_idade['Estado'] == 'Sul')
tab3_44_idade.drop(tab3_44_idade[selecao].index,inplace=True)
tab3_44_idade.reset_index(drop=True,inplace=True)

In [51]:
tab3_44_idade.loc[0:7, 'Região'] = 'Norte'
tab3_44_idade.loc[7:16, 'Região'] = 'Nordeste'
tab3_44_idade.loc[16:20, 'Região'] = 'Sudeste'
tab3_44_idade.loc[20:23, 'Região'] = 'Sul'
tab3_44_idade.loc[23:, 'Região'] = 'Centro-Oeste'