In [32]:
import pandas as pd

# Tab 3.44
## Sheet 1 - Proporção de diagnosticos de depressão de acordo com o sexo

In [33]:
tab3_44_sexo = pd.read_excel('dados/3.44.xls')

### Removendo colunas desnecessárias

In [34]:
tab3_44_sexo.dropna(inplace=True)
tab3_44_sexo.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 5','Unnamed: 6','Unnamed: 8','Unnamed: 9'],inplace=True)

### Renomeando colunas

In [35]:
colunas = ['Estado','Diagnostico Depressão Total', 'Diagnostico Depressão Masculino', 'Diagnostico Depressão Feminino']
tab3_44_sexo.columns = colunas

In [36]:
tab3_44_sexo.head(5)

,Estado,Diagnostico Depressão Total,Diagnostico Depressão Masculino,Diagnostico Depressão Feminino
8,Brasil,10.2,5.1,14.7
9,Urbana,10.7,5.4,15.1
10,Rural,7.6,3.5,12.3
11,Norte,5,2.9,7
12,Rondônia,9,5.1,12.8

### Removendo linhas com dados totais do brasil e de regiões, mantando apenas as colunas de cada estado

In [37]:
tab3_44_sexo.drop(tab3_44_sexo.iloc[0:3].index,inplace=True)
selecao = (tab3_44_sexo['Estado'] == 'Norte') | (tab3_44_sexo['Estado'] == 'Nordeste') | (tab3_44_sexo['Estado'] == 'Sudeste') | (tab3_44_sexo['Estado'] == 'Centro-Oeste') | (tab3_44_sexo['Estado'] == 'Sul')
tab3_44_sexo.drop(tab3_44_sexo[selecao].index,inplace=True)
tab3_44_sexo.reset_index(drop=True,inplace=True)

In [38]:
tab3_44_sexo.reset_index(drop=True,inplace=True)

In [39]:
tab3_44_sexo.loc[0:7, 'Região'] = 'Norte'
tab3_44_sexo.loc[7:16, 'Região'] = 'Nordeste'
tab3_44_sexo.loc[16:20, 'Região'] = 'Sudeste'
tab3_44_sexo.loc[20:23, 'Região'] = 'Sul'
tab3_44_sexo.loc[23:, 'Região'] = 'Centro-Oeste'

### Corrigindo tipo de colunas numericas

In [40]:
tab3_44_sexo.dtypes

Estado                             object
Diagnostico Depressão Total        object
Diagnostico Depressão Masculino    object
Diagnostico Depressão Feminino     object
Região                             object
dtype: object

In [41]:
colunas_numericas = ['Diagnostico Depressão Total', 'Diagnostico Depressão Masculino', 'Diagnostico Depressão Feminino']
tab3_44_sexo[colunas_numericas] = tab3_44_sexo[colunas_numericas].apply(pd.to_numeric, errors='coerce')
tab3_44_sexo.head()

,Estado,Diagnostico Depressão Total,Diagnostico Depressão Masculino,Diagnostico Depressão Feminino,Região
0,Rondônia,9.0,5.1,12.8,Norte
1,Acre,6.0,2.5,9.3,Norte
2,Amazonas,4.2,2.9,5.4,Norte
3,Roraima,5.1,2.8,7.3,Norte
4,Pará,4.1,2.5,5.6,Norte

## Sheet 2 - Proporção de diagnosticos de depressão por grupo de idade

### Importando tabela

In [42]:
tab3_44_idade = pd.read_excel('dados/3.44.xls',sheet_name='grupos_de_idade')

### Removendo dados nulos e mantendo somente colunas relevantes

In [44]:
colunas = [2,3,5,6,8,9,10,12,13,15,16,18,19]
tab3_44_idade.dropna(inplace=True)
tab3_44_idade.drop(columns=tab3_44_idade.columns[colunas],inplace=True)
tab3_44_idade.head(10)

,"Tabela 3.44.2.1 - Proporção de pessoas de 18 anos ou mais de idade que referem diagnóstico de depressão por profissional de saúde mental, por grupos de idade, com indicação do intervalo de confiança de 95%, segundo as Grandes Regiões, as Unidades da Federação e a situação do domicílio - 2019",Unnamed: 1,Unnamed: 4,Unnamed: 7,Unnamed: 11,Unnamed: 14,Unnamed: 17
8,Brasil,10.2,5.9,11.3,13.2,11.8,10.2
9,Urbana,10.7,6.2,11.7,13.9,12.1,10.8
10,Rural,7.6,3.8,8.8,9,9.7,6.6
11,Norte,5,3.2,5.6,5.7,6.3,5.2
12,Rondônia,9,7.2,9.9,6.9,10.9,6.6
13,Acre,6,2.7,7.6,5.9,9.7,2
14,Amazonas,4.2,4,4,5.8,6.6,2.2
15,Roraima,5.1,4.8,5.2,3.4,7.1,4.1
16,Pará,4.1,1.7,5.1,5.1,4,6.4
17,Amapá,4.5,4.8,3.7,4.3,10.7,5.5

### Renomeando colunas

In [48]:
colunas = ['Estado','Diagnosticos Depressão Total','Diagnosticos Depressão 18 a 19 anos','Diagnosticos Depressão 30 a 59 anos','Diagnosticos Depressão 60 a 64 anos','Diagnosticos Depressão 65 a 74 anos','Diagnosticos Depressão 75 anos ou mais']
tab3_44_idade.columns = colunas
tab3_44_idade.head(10)

,Estado,Diagnosticos Depressão Total,Diagnosticos Depressão 18 a 19 anos,Diagnosticos Depressão 30 a 59 anos,Diagnosticos Depressão 60 a 64 anos,Diagnosticos Depressão 65 a 74 anos,Diagnosticos Depressão 75 anos ou mais
8,Brasil,10.2,5.9,11.3,13.2,11.8,10.2
9,Urbana,10.7,6.2,11.7,13.9,12.1,10.8
10,Rural,7.6,3.8,8.8,9,9.7,6.6
11,Norte,5,3.2,5.6,5.7,6.3,5.2
12,Rondônia,9,7.2,9.9,6.9,10.9,6.6
13,Acre,6,2.7,7.6,5.9,9.7,2
14,Amazonas,4.2,4,4,5.8,6.6,2.2
15,Roraima,5.1,4.8,5.2,3.4,7.1,4.1
16,Pará,4.1,1.7,5.1,5.1,4,6.4
17,Amapá,4.5,4.8,3.7,4.3,10.7,5.5

### Removendo linhas de dados gerais do Brasil e Regiões

In [49]:
tab3_44_idade.drop(tab3_44_idade.iloc[0:3].index,inplace=True)
selecao = (tab3_44_idade['Estado'] == 'Norte') | (tab3_44_idade['Estado'] == 'Nordeste') | (tab3_44_idade['Estado'] == 'Sudeste') | (tab3_44_idade['Estado'] == 'Centro-Oeste') | (tab3_44_idade['Estado'] == 'Sul')
tab3_44_idade.drop(tab3_44_idade[selecao].index,inplace=True)
tab3_44_idade.reset_index(drop=True,inplace=True)

### Criando coluna de região

In [51]:
tab3_44_idade.loc[0:7, 'Região'] = 'Norte'
tab3_44_idade.loc[7:16, 'Região'] = 'Nordeste'
tab3_44_idade.loc[16:20, 'Região'] = 'Sudeste'
tab3_44_idade.loc[20:23, 'Região'] = 'Sul'
tab3_44_idade.loc[23:, 'Região'] = 'Centro-Oeste'

## Sheet 3 - Proporção de diagnosticos de depressão por nivel de instrução

In [55]:
tab3_44_instrucao = pd.read_excel('dados/3.44.xls',sheet_name='nivel_de_instrucao')

In [56]:
colunas = [2,3,5,6,8,9,11,12,14,15]
tab3_44_instrucao.dropna(inplace=True)
tab3_44_instrucao.drop(columns=tab3_44_instrucao.columns[colunas],inplace=True)
tab3_44_instrucao.head(10)

,"Tabela 3.44.3.1 - Proporção de pessoas de 18 anos ou mais de idade que referem diagnóstico de depressão por profissional de saúde mental, por nível de instrução, com indicação do intervalo de confiança de 95%, segundo as Grandes Regiões, as Unidades da Federação e a situação do domicílio - 2019",Unnamed: 1,Unnamed: 4,Unnamed: 7,Unnamed: 10,Unnamed: 13
8,Brasil,10.2,10.9,9.4,9,12.2
9,Urbana,10.7,11.9,9.9,9.2,12.2
10,Rural,7.6,7.9,6.2,7.1,12.4
11,Norte,5,5.1,4.8,4.4,6.5
12,Rondônia,9,8.5,8.4,9.8,9.5
13,Acre,6,6.2,3.9,5.9,7.5
14,Amazonas,4.2,4.1,5.9,3.2,5.2
15,Roraima,5.1,4.4,4.1,4.4,8.3
16,Pará,4.1,4.6,3.2,3.8,5.2
17,Amapá,4.5,3.1,1.7,5.2,8.4

In [60]:
colunas = ['Estado','Diagnosticos Depressão Total','Sem instrução e fundamental incompleto','Fundamental completo e médio incompleto','Médio completo e superior incompleto','Superior completo']
tab3_44_instrucao.columns = colunas
tab3_44_instrucao.head(10)

,Estado,Diagnosticos Depressão Total,Sem instrução e fundamental incompleto,Fundamental completo e médio incompleto,Médio completo e superior incompleto,Superior completo
8,Brasil,10.2,10.9,9.4,9,12.2
9,Urbana,10.7,11.9,9.9,9.2,12.2
10,Rural,7.6,7.9,6.2,7.1,12.4
11,Norte,5,5.1,4.8,4.4,6.5
12,Rondônia,9,8.5,8.4,9.8,9.5
13,Acre,6,6.2,3.9,5.9,7.5
14,Amazonas,4.2,4.1,5.9,3.2,5.2
15,Roraima,5.1,4.4,4.1,4.4,8.3
16,Pará,4.1,4.6,3.2,3.8,5.2
17,Amapá,4.5,3.1,1.7,5.2,8.4

In [61]:
tab3_44_instrucao.drop(tab3_44_instrucao.iloc[0:3].index,inplace=True)
selecao = (tab3_44_instrucao['Estado'] == 'Norte') | (tab3_44_instrucao['Estado'] == 'Nordeste') | (tab3_44_instrucao['Estado'] == 'Sudeste') | (tab3_44_instrucao['Estado'] == 'Centro-Oeste') | (tab3_44_instrucao['Estado'] == 'Sul')
tab3_44_instrucao.drop(tab3_44_instrucao[selecao].index,inplace=True)
tab3_44_instrucao.reset_index(drop=True,inplace=True)

In [63]:
tab3_44_instrucao.loc[0:7, 'Região'] = 'Norte'
tab3_44_instrucao.loc[7:16, 'Região'] = 'Nordeste'
tab3_44_instrucao.loc[16:20, 'Região'] = 'Sudeste'
tab3_44_instrucao.loc[20:23, 'Região'] = 'Sul'
tab3_44_instrucao.loc[23:, 'Região'] = 'Centro-Oeste'

In [67]:
tab3_44_instrucao.sample(5)

,Estado,Diagnosticos Depressão Total,Sem instrução e fundamental incompleto,Fundamental completo e médio incompleto,Médio completo e superior incompleto,Superior completo,Região
13,Alagoas,6.2,7.1,7.2,4.4,6,Nordeste
24,Mato Grosso,8.2,7.4,9.7,6.9,10.9,Centro-Oeste
25,Goiás,12,13.4,5.4,12.9,14.2,Centro-Oeste
26,Distrito Federal,9.4,8.6,15.6,7.5,10.2,Centro-Oeste
5,Amapá,4.5,3.1,1.7,5.2,8.4,Norte

## Sheet 3 - Proporção de diagnosticos de depressão por nivel de instrução

In [76]:
def tratamento_dataset(dataset,colunas_remocao,nomes_colunas): 
    dataset.dropna(inplace=True)
    dataset.drop(columns=dataset.columns[colunas_remocao],inplace=True)

    dataset.columns = nomes_colunas

    dataset.drop(dataset.iloc[0:3].index,inplace=True)
    selecao = (dataset['Estado'] == 'Norte') | (dataset['Estado'] == 'Nordeste') | (dataset['Estado'] == 'Sudeste') | (dataset['Estado'] == 'Centro-Oeste') | (dataset['Estado'] == 'Sul')
    dataset.drop(dataset[selecao].index,inplace=True)
    dataset.reset_index(drop=True,inplace=True)

    dataset.loc[0:7, 'Região'] = 'Norte'
    dataset.loc[7:16, 'Região'] = 'Nordeste'
    dataset.loc[16:20, 'Região'] = 'Sudeste'
    dataset.loc[20:23, 'Região'] = 'Sul'
    dataset.loc[23:, 'Região'] = 'Centro-Oeste'

    return dataset
    

tab3_44_corRaca = pd.read_excel('dados/3.44.xls',sheet_name='cor_ou_raca')
colunas_remocao = [2,3,5,6,8,9,11,12]
nomes_colunas = ['Estado','Diagnosticos depressão total','Branca','Preta','Parda']
tab3_44_corRaca = tratamento_dataset(tab3_44_corRaca,colunas_remocao,nomes_colunas)
tab3_44_corRaca.sample(5)

,Estado,Diagnosticos depressão total,Branca,Preta,Parda,Região
20,Paraná,13.9,14.4,17.5,12.9,Sul
6,Tocantins,6.6,7.8,5.1,6.7,Norte
24,Mato Grosso,8.2,9.8,6.4,7.8,Centro-Oeste
17,Espírito Santo,11.3,11.1,6.9,12.5,Sudeste
1,Acre,6,5.7,4.5,6.3,Norte

In [77]:
tab3_44_posOcup = pd.read_excel('dados/3.44.xls',sheet_name='pos ocup')
colunas_remocao = [2,3,5,6,8,9,11,12]
nomes_colunas = ['Estado','Diagnosticos depressão total','trabalhando_ocupadas','trabalhando_desocupadas','desempregadas']
tab3_44_posOcup = tratamento_dataset(tab3_44_posOcup,colunas_remocao,nomes_colunas)
tab3_44_posOcup.sample(5)

,Estado,Diagnosticos depressão total,trabalhando_ocupadas,trabalhando_desocupadas,desempregadas,Região
26,Distrito Federal,9.4,8.8,8.2,11.4,Centro-Oeste
6,Tocantins,6.6,5.3,13.8,8,Norte
24,Mato Grosso,8.2,7.4,3.4,10.6,Centro-Oeste
11,Paraíba,7.6,6.2,4.9,9.7,Nordeste
3,Roraima,5.1,4.2,2.2,7.7,Norte

In [80]:
tab3_44_rendimento = pd.read_excel('dados/3.44.xls',sheet_name='rendimento')
colunas_remocao = [2,3,5,6,8,9,11,12,13,15,16,18,19,21,22,24,25]
nomes_colunas = ['Estado','Diagnosticos depressão total','sem rendimento e ate 1/4 do salario minimo','mais de 1/4 a 1/2 do salario minimo','mais de 1/2 a 1 salario minimo','mais de 1 a 2 salarios minimos', 'mais de 2 a 3 salarios minimos', 'mais de 3 a 5 salarios minimos', 'mais de 5 salarios minimos']
tab3_44_rendimento = tratamento_dataset(tab3_44_rendimento,colunas_remocao,nomes_colunas)
tab3_44_rendimento.sample(5)

,Estado,Diagnosticos depressão total,sem rendimento e ate 1/4 do salario minimo,mais de 1/4 a 1/2 do salario minimo,mais de 1/2 a 1 salario minimo,mais de 1 a 2 salarios minimos,mais de 2 a 3 salarios minimos,mais de 3 a 5 salarios minimos,mais de 5 salarios minimos,Região
1,Acre,6,7,6.9,4.4,4.8,7.6,8.5,7.7,Norte
11,Paraíba,7.6,5.5,7.9,6.8,9.9,7.8,6.6,12.1,Nordeste
6,Tocantins,6.6,4.3,6,5.9,8.5,8.7,6.7,11.4,Norte
13,Alagoas,6.2,5.9,6.3,6.2,6.2,6.2,10.6,2.7,Nordeste
12,Pernambuco,6.8,7.9,5.8,6.6,5.7,3,15,13.3,Nordeste